{
  config,
  lib,
  ...
}:
let
  cfg = config.services.forgeExample;
in
# 实现逻辑：读取 options 产出系统配置。
# 规范要点：所有对系统的改动（写文件、启服务、装包）必须包在 lib.mkIf cfg.enable 里。
{
  config = lib.mkIf cfg.enable {
    environment.etc."forge-example.conf".text = ''
      # generated by nix-forge (modules/nixos/forge-example)
      message = ${cfg.message}
    '';
  };
}
